FROM node:23-bullseye
LABEL org.opencontainers.image.authors="stephen@stephenneal.net"

WORKDIR /var/www

# Update OS
# Install bash & NPM
# Install Yarn using NPM
RUN apt-get update \
    && apt-get install \
    	bash